@startuml

skinparam state {
  BackgroundColor #F0F8FF
  BorderColor #333
  FontSize 14
  FontName Arial
  Padding 15
  ArrowFontSize 12
}

hide empty description

[*] --> INICIO

INICIO --> Sistema : login 

state Sistema {
    MENU_PRINCIPAL --> NUEVA_PUBLICACION

    NUEVA_PUBLICACION --> CREAR_PUBLICACION_HABITACION

    CREAR_PUBLICACION_HABITACION --> VER_PUBLICACIONES_HABITACION

    NUEVA_PUBLICACION --> CREAR_PUBLICACION_PERFIL

    CREAR_PUBLICACION_PERFIL --> VER_PUBLICACIONES_PERFIL

    MENU_PRINCIPAL --> VER_PUBLICACIONES_HABITACION
        note left of VER_PUBLICACIONES_HABITACION
            listarPublicaciones
            verDetalle
            filtrarPublicaciones
        end note

    MENU_PRINCIPAL --> VER_PUBLICACIONES_PERFIL
        note right of VER_PUBLICACIONES_PERFIL
            listarPublicaciones
            verDetalle
            filtrarPublicaciones
        end note

    MENU_PRINCIPAL --> VER_MI_PERFIL
        note on link
            editarPerfil
        end note

    VER_MI_PERFIL --> MIS_PUBLICACIONES
        note on link
            listarPublicaciones
            editarPublicacion
            ocultarActivarPublicacion
            borrarPublicacion
        end note
}

Sistema --> [*] : logout

@enduml